In [18]:
a <- "Apple"
b <- "12.4"
print(paste(class(a), class(b)))

[1] "character character"


In [16]:
c <- 12.3
d <- -0.76
e <- 0
print(paste(class(c), class(d), class(e)))

[1] "numeric numeric numeric"


In [27]:
f <- integer(7)
g <- integer(8.2)
print(paste(class(f), class(g)))
print(g)

[1] "integer integer"
[1] 0 0 0 0 0 0 0 0


In [28]:
h <- 2 + 4i
print(class(h))

[1] "complex"


In [32]:
i <- TRUE
j <- FALSE
k <- F
print(paste(class(i), class(j), class(k)))
print(k)

[1] "logical logical logical"
[1] FALSE


In [36]:
l <- c(1, 2, 12.0)
m <- c("ABC", "PQ")
n <- c("ABC", 12)
print(paste(class(l), class(m), class(n)))

[1] "numeric character character"


In [39]:
o <- list("ABC", 12)
print(class(o))
print(paste(o[1], o[2]))

[1] "list"
[1] "ABC 12"


In [42]:
p <- c("ABC", 12, "PQ", 12, 1, 12, "ABC")
f_p <- factor(p)
print(class(f_p))
print(f_p)

[1] "factor"
[1] ABC 12  PQ  12  1   12  ABC
Levels: 1 12 ABC PQ


In [46]:
q <- NA
r <- 0
s <- 12
t <- 0/0
print(paste(class(q), class(t)))
print(is.na(q))
print(paste(is.na(t), is.nan(t)))

[1] "logical numeric"
[1] TRUE
[1] "TRUE TRUE"


In [47]:
u <- matrix(c(1, 1, 13, 1, 4, 34, 45, 98), 2, 4)
print(class(u))
print(u)

[1] "matrix"
     [,1] [,2] [,3] [,4]
[1,]    1   13    4   45
[2,]    1    1   34   98


In [50]:
v <- 1:5
w <- 100:96
vw1 <- cbind(v, w)
vw2 <- rbind(v, w)
print(paste(class(vw1), class(vw2)))
print(vw1)
print(vw2)

[1] "matrix matrix"
     v   w
[1,] 1 100
[2,] 2  99
[3,] 3  98
[4,] 4  97
[5,] 5  96
  [,1] [,2] [,3] [,4] [,5]
v    1    2    3    4    5
w  100   99   98   97   96


In [51]:
x <- 1
y <- 100:96
xy <- rbind(x, y)
print(xy)

  [,1] [,2] [,3] [,4] [,5]
x    1    1    1    1    1
y  100   99   98   97   96


In [55]:
z1 <- array(dim=c(5))
z2 <- array(dim=c(5, 6))
print(paste(class(z1), class(z2)))
print(z1)
print(z2)

[1] "array matrix"
[1] NA NA NA NA NA
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]   NA   NA   NA   NA   NA   NA
[2,]   NA   NA   NA   NA   NA   NA
[3,]   NA   NA   NA   NA   NA   NA
[4,]   NA   NA   NA   NA   NA   NA
[5,]   NA   NA   NA   NA   NA   NA


In [64]:
z2[3,3] <- 1
z2

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    NA   NA   NA   NA   NA  
[2,] 2    NA   NA   NA   NA   NA  
[3,] 3    NA    1   NA   NA   NA  
[4,] 4    NA   NA   NA   NA   NA  
[5,] 5    NA   NA   NA   NA   NA

**typeof** determines the (R internal) type or storage mode of any object 

R possesses a simple generic function mechanism which can be used for an object-oriented style of programming. Method dispatch takes place based on the **class** of the first argument to the generic function.

In [86]:
name <- c("Abyss", "Benjamin", "Chloe")
id <- c(101, 102, 103)
msalary <- c(5000, 8000, 10000)
df <- data.frame(name, id, msalary)
print(class(df))
print(typeof(df))
print(df)

[1] "data.frame"
[1] "list"
      name  id msalary
1    Abyss 101    5000
2 Benjamin 102    8000
3    Chloe 103   10000


In [73]:
print(colnames(df))
print(names(df)) #Names works only for dataframes

[1] "name"    "id"      "msalary"
[1] "name"    "id"      "msalary"


In [78]:
names(df)[3] <- "expenditure"
df

name     id  expenditure
1 Abyss    101  5000      
2 Benjamin 102  8000      
3 Chloe    103 10000